name: Build all examples

on:
  workflow_dispatch:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: carlosperate/arm-none-eabi-gcc-action@v1
    - uses: actions/checkout@v4

    - name: Install ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Checkout stm32-cmake
      uses: actions/checkout@v4
      with:
        repository: ObKo/stm32-cmake
        path: stm32-cmake 
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja ${{github.workspace}}/example

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}